### PR TITLE
Pool connection requests to improve speed

### PR DESCRIPTION
**Pull request by tobiemh**
Use node.js http agent for pooling sockets for the http requests.

### CODE REVIEW

**Comment by herenow** [comment]
Good idea, thanks! I'll add some documentation on the feature.

**Comment by justmoon** [comment]
This change actually reduced speed for us by about 3x.

Here are the `npm test` times for our project:

Roachjs 0.2.16:

```
  55 passing (2s)
  3 pending

npm info posttest [removed]
npm info ok 
npm test  2.66s user 0.30s system 90% cpu 3.291 total
```

Roachjs 0.2.17:

```
  55 passing (8s)
  3 pending

npm info posttest [removed]
npm info ok 
npm test  2.70s user 0.28s system 32% cpu 9.321 total
```

Note that the Node process still consumes about the same amount of CPU time, but in real-time, the tests got nearly 3x slower.

CockroachDB's requests are long-running and blocking. So if you're using a connection pool, you'll remove the latency of setting up new connections, but you'll risk having a lot of requests waiting behind other requests.

One solution would be to set a huge limit on the pool, but those connections will be kept open and the number of open connections is a finite resource, too.

The ideal solution would be HTTP2, so you could have a single multiplexed connection. That would remove both the connection latency as well as the head-of-line blocking, i.e. cake+eat. I'll go lobby for that upstream.

In the meantime, my vote is to make connection pooling a config option and default it to off. I think you're much more likely to run into the head-of-line blocking issue (which can degrade performance by many multiples) than you care about the latency of setting up new connections (which is a fixed delay per request.)

**Comment by herenow** [comment]
@justmoon 
Cockroach's client has recently moved to Go's RPC package.

So yes, we should lobby for HTTP2 :+1: 

We could also give a custom `agent` option instead of `sockets`.

But I'm still not quite sure why this change is any different from using the default `http.globalAgent` which also does pooling, from my understanding. Is the default actually no connection pooling?

**Comment by tobiemh** [comment]
@herenow 

A custom agent option might make more sense, allowing it to be disabled if needed. An alternative could be a `pooling` option (disable/enable `keepAlive` on the Agent).

By default each request uses the `http.globalAgent`, but this has `keepAlive` turned off by default (so no connection pooling). By adding a custom agent, `keepAlive` is turned on.

@justmoon 

For us the tests were an order of magnitude quicker, but yes I guess that depending on the use case this could make it slower. In addition I agree with the 'connections will be kept open' point.

The change set the default max sockets to 5 (probably fewer than the default concurrent connections when using the default `http.globalAgent` without `keepAlive` turned on). This could have affected the test speed?

**Comment by justmoon** [comment]
Indeed you're correct, Node does use pooling by default. And it seems like it defaults to `maxSockets = Infinity` and `maxFreeSockets = 256`, so the degradation most likely comes from reducing the limit from Infinity/256 to 5/5.

**Comment by herenow** [comment]
@herenow @justmoon 
I thought the default was `5` not `Infinity`, I think it changed on node > v0.11, since in node v0.10 `require('http').globalAgent.maxSockets` gives me `5` and node v0.11 `Infinity`. Reading the docs again, confirms this change.

@edit

A solution would be to set the default maximum "sockets" pool to `opts.sockets || this.http.globalAgent.maxSockets` but I prefer giving an optional `agent` interface to use.

**Comment by justmoon** [comment]
@tobiemh Which Node version did you see the improvement on?

I'm using iojs 2.0.2. Setting sockets = Infinity does indeed bring it back to the 0.2.16 performance level.

**Comment by tobiemh** [comment]
@justmoon The test was using v0.12.2, and `require('http').globalAgent.maxSockets` = Infinity.

I suppose it depends on how you have CockroachDB setup for the tests?

**Comment by herenow** [comment]
@justmoon @tobiemh 

Well, after reading the docs, I'm in favor of using a custom `Agent` by default, with `keepAlive` enabled by default. If anyone want's to turn this off or tweak, they could send in `globalAgent` or their own `Agent` through the clients `agent` option. Since atm the only transport option is http I think the `agent` option is ok, rather then `pooling` + `maxSocket`.

Note: that `maxSockets` will default to `Infinity` on node > v0.11.x or `5` on node < v0.10.x

Do you guys agree?

@edit
I've made the change, let me know if there are any problems.

**Pull request merged**
